// <auto-generated />
namespace BuildSpecTool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Main_Models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Main_Models));
        
        string IMigrationMetadata.Id
        {
            get { return "201712270426530_add_Main_Models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
